version: "3.9"

services:
  elixir:
    build: ./elixir
    container_name: elixir_system
    ports:
      - "8001:8000"

  elixir-express:
    build: ./elixir-express
    container_name: express_elixir_system
    ports:
      - "8002:8000"

  sorbnet:
    build: ./sorbnet
    container_name: sorbnet_system
    ports:
      - "8003:8000"