server.port=8082
spring.application.name=sorbnet

# Kafka - dynamiczny adres (localhost gdy lokalnie, kafka:9092 gdy Docker)
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.consumer.group-id=sorbnet-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.isolation-level=read_committed
spring.kafka.producer.enable-idempotence=true

# Baza danych YugabyteDB
spring.datasource.url=jdbc:yugabytedb://localhost:5460/yugabyte
spring.datasource.username=yugabyte
spring.datasource.password=yugabyte
spring.datasource.driver-class-name=com.yugabyte.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Czas po którym bank jest blokowany przy przekroczeniu limitu (domyślnie 2h)
sorbnet.overlimit.block-after-hours=2
# Jak często odpala się gridlock resolution (ms)
sorbnet.gridlock.interval-ms=30000

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true