server.port=8080
spring.application.name=sorbnet

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.consumer.group-id=sorbnet-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.isolation-level=read_uncommitted
spring.kafka.producer.enable-idempotence=true
spring.kafka.consumer.max-poll-records=500
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5460/sorbnet}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:yugabyte}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:yugabyte}
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.pl.pz.sorbnet=DEBUG
logging.level.org.springframework.web=DEBUG
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

sorbnet.overlimit.block-after-hours=2
sorbnet.gridlock.interval-ms=30000

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true