spring.application.name=elixir

server.port=8080

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5460/elixir}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:yugabyte}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:yugabyte}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#springdoc.swagger-ui.path=/swagger-ui.html
spring.mvc.contentnegotiation.default-content-type=application/json
#15 min sesji testowej
elixir.session.interval= 10000


